#!/usr/bin/perl

=head1 NAME

ipmi_fancontrol-ng - IPMI Fan Control for IBM System x3650 M5

=head1 SYNOPSIS

    ./ipmi_fancontrol-ng

=head1 DESCRIPTION

This script controls IPMI compatible server's fan speeds in response to CPU
temperatures provided by lm-sensors. This script has been tested on a Dell
PowerEdge R210 II and ported for IBM System x3650 M4/M5, but should work on
any IPMI compatible server.

The script puts your server into "Full Fan Speed Mode", and then modifies what
"Full Speed" means. You have to manually use IPMI to set it to e.g. "Optimal"
when you're not using the script.

=head2 IBM x3650 Port Notes

This port was made in an attempt to quiet down an IBM system x3650 M5. The
porting involved changing the raw commands, removing the GetFanRPM function as
it was useless in this scenario, and IBM lists their fans as 1A 1B 2A 2B.

The IMM2 maintains partial control over the fans' actual speed. For example,
setting the fans at 30% results in an actual fan speed of roughly 24%.
Sometimes the script fails to update and the IMM2 takes control back over the
fan speed controls. Overall, the real speed settings feel very coarse.

=head2 What's New

The original script provided a "step" approach where fans would take large
"steps" depending on the temperatures. In this version, scalar equations are
generated to provide an easy (and quiet) slope to follow to the next step.
These equations are simple Y=mx+b linear slopes that effectively provide a fan
"curve" based on the entries in the %cpu_temp_to_fan_speed hash table.

=head1 AUTHORS

=over 4

=item * Maintainer: Brian Wilson <brian@wiltech.org>

=item * Original Author: Layla Mah <layla@insightfulvr.com>

=item * Original Version: https://github.com/missmah/ipmi_tools

=back

=head1 WARNING

B<WARNING:> You use this script at your own risk, and no warranty is provided.
Do not use in production environments.

=head1 LICENSE

See the LICENSE file included with this distribution.

=cut

use strict;
use warnings;

use List::Util qw[min max];

# System Configuration
my $hostname            = `hostname`;
# Remove line ending from $hostname
$hostname =~ s/\n//g;

my $number_of_cpus      = 2; # Number of CPUs to search for
#my $number_of_gpus      = 4; # Number of GPUs to search for
my $number_of_fans      = 6; # Number of FANs to search for
my $number_of_fanbanks  = 2; # Number of BANKs of FANs to update
#my $number_of_fanbanks  = 2; # Number of BANKs of FANs to update
my $min_temp_change     = 0; # *C minimum change to actually cause a fan speed update
my $seconds_to_sleep    = 3; # Number of seconds to sleep between update loops

# IPMI Configuration
#my $ipmi_username       = "username_goes_here";
#my $ipmi_password       = "password_goes_here";
#my $ipmi_ipaddress      = "ip_address_goes_here";
my $ipmi_cmd_listall    = "sdr list full";
#my $ipmi_connectmode    = "open";
my $ipmi_preamble       = "ipmitool";

# Not needed as it's running directly on proxmox as a service
#my $ipmi_preamble       = "ipmitool -I $ipmi_connectmode";
#my $ipmi_preamble       = 'ipmitool -I $ipmi_connectmode -U $ipmi_username -P $ipmi_password -H $ipmi_ipaddress';

# CPU Temp -> Fan Speed Mappings
my %cpu_temp_to_fan_speed;
$cpu_temp_to_fan_speed{80} = 250;
$cpu_temp_to_fan_speed{70} = 150;
$cpu_temp_to_fan_speed{55} = 50;
$cpu_temp_to_fan_speed{40} = 25;
$cpu_temp_to_fan_speed{10} = 5;

my %cpu_temp_scale;

=head1 IMPLEMENTATION

=head2 Global Variables

=over 4

=item * $g_current_fan_duty_cycle - Current fan duty cycle percentage

=item * $g_current_gpu_temp - Current GPU temperature

=item * $g_current_cpu_temp - Current CPU temperature

=item * $g_last_set_cpu_temp - Last CPU temperature when fan speed was updated

=item * $g_last_set_gpu_temp - Last GPU temperature when fan speed was updated

=back

=cut

my $g_current_fan_duty_cycle = 0;
my $g_current_gpu_temp = 0;
my $g_current_cpu_temp = 0;
my $g_last_set_cpu_temp = 0;
my $g_last_set_gpu_temp = 0;

=head2 Internal_DoSetFanSpeed

Sets the fan speed for each individual fan bank using IPMI raw commands.

=over 4

=item Parameters: $fan_speed - The desired fan speed percentage (0-100)

=back

=cut

sub Internal_DoSetFanSpeed
{
    my ( $fan_speed ) = @_;

    # Sets the speed for each individual fan
    for (my $i = 1; $i <= $number_of_fanbanks; $i++)
    {
        print "Setting FanBank n°$i speed at $fan_speed\n";
        #ipmitool raw 0x3a 0x07 1 100 0
        `$ipmi_preamble raw 0x3a 0x07 $i $fan_speed 0x01> /dev/null 2>&1`;
    }
}

=head2 SetFanSpeed

Sets the fan speed if temperature change exceeds minimum threshold.

=over 4

=item Parameters: $fan_speed - The desired fan speed percentage (0-100)

=back

=cut

sub SetFanSpeed
{
    my ( $fan_speed ) = @_;

    my $cpu_temp_difference = $g_current_cpu_temp - $g_last_set_cpu_temp;
    my $gpu_temp_difference = $g_current_gpu_temp - $g_last_set_gpu_temp;
    if( ( (abs $cpu_temp_difference) > $min_temp_change ) or ( (abs $gpu_temp_difference) > $min_temp_change ) )
    {
        # Set all 4 fan banks to operate at $fan_speed duty cycle (0x0-0x64 valid range)
        print "\n";
        print "********************** Updating Fan Speeds **********************\n";
        print "We last updated fan speed $cpu_temp_difference *C ago (CPU Temperature).\n";
        print "We last updated fan speed $gpu_temp_difference *C ago (GPU Temperature).\n";
        print "Current CPU Temperature is $g_current_cpu_temp *C.\n";
        print "Current GPU Temperature is $g_current_gpu_temp *C.\n";
        print "*****************************************************************\n";

        $g_last_set_cpu_temp = $g_current_cpu_temp;
        $g_last_set_gpu_temp = $g_current_gpu_temp;
        $g_current_fan_duty_cycle = $fan_speed;

        Internal_DoSetFanSpeed( $fan_speed );
    }
}

=head2 GetCPUTemp

Get current CPU temperature from lmsensors. If there are multiple CPUs,
the script will automatically choose the highest temperature.

=over 4

=item Returns: Maximum CPU temperature in degrees Celsius

=back

=cut

# Get current CPU temperature from lmsensors. If there are multiple CPU's,
# the script will automatically choose the highest temperature.
sub GetCPUTemp
{
    my $current_cpu_temp = 0;

    my $sensors_output = `sensors | grep "Package" | sed 's/.*:\\s*+\\(.*\\)  .*(.*/\\1/'`;
    my @vals = split("\n", $sensors_output);
    foreach my $value (@vals)
    {
        # Remove the *C from $sensors_output (and anything else thats not numbers or decimal points)
        my $cpu_temp = `echo $value | sed -e 's/[^0-9. ]*//g' -e 's/ \\+/ /g'`;
        $current_cpu_temp = max($cpu_temp, $current_cpu_temp);
    }
    # Remove trailing line endings
    $current_cpu_temp =~ s/\n//g;

    return $current_cpu_temp;
}

=head2 CalculateScalars

Calculates the linear interpolation coefficients (slope and y-intercept)
for each temperature range based on the cpu_temp_to_fan_speed hash.
This creates smooth transitions between temperature points.

=cut

sub CalculateScalars
{
    my @previous = ();
    foreach my $a (sort keys %cpu_temp_to_fan_speed){
        my @current = ($a, $cpu_temp_to_fan_speed{$a});

        if (@previous) {
            my $m = ($current[1] - $previous[1]) / ($current[0] - $previous[0]);
            my $b = $current[1] - ($m*$current[0]);

            $cpu_temp_scale{$a} = [($m, $b)];
        }

        @previous = @current;
    }
}

=head2 UpdateFanSpeed

Main update loop function that reads current temperatures, calculates desired
fan speeds using linear interpolation, and updates the fans accordingly.
Also outputs metrics to InfluxDB format for monitoring.

=cut

sub UpdateFanSpeed
{
    my $current_cpu_temp = GetCPUTemp();
    my $current_gpu_temp = 0;

    $g_current_cpu_temp = $current_cpu_temp;
    $g_current_gpu_temp = $current_gpu_temp;

    print "Maximum CPU Temperature Seen: $current_cpu_temp degrees C.\n";
    print "Maximum GPU Temperature Seen: $current_gpu_temp degrees C.\n";

    my $desired_fan_speed = 0;
    my $calculated_speed = 0;
    foreach my $a (reverse sort keys %cpu_temp_scale) {
        #print "A$a\n";
        if ($current_cpu_temp <= $a) {
            my @formula = @{$cpu_temp_scale{$a}};
            $calculated_speed = ($formula[0] * $current_cpu_temp) + $formula[1];
            #print "Test#2:$formula[0] $formula[1]\n";
            $desired_fan_speed = sprintf("%.0f", $calculated_speed);
        }
    }

    print "Current Fan Duty Cycle: $g_current_fan_duty_cycle%\n";
    print "Desired Fan Duty Cycle: $desired_fan_speed%\n";


    # Output basic InfluxDB metrics to /tmp/fan_speed_telegraf
    my $speed_raw = sprintf("%x", $calculated_speed);
    open(FH, '>', '/tmp/fan_speed_telegraf') or die $!;
    print FH "fans,host=$hostname speed_percent=$calculated_speed\n";
    print FH "fans,host=$hostname speed_raw=$speed_raw\n";
    close(FH);

    SetFanSpeed($desired_fan_speed);
}

print "Starting.\n";
CalculateScalars();

while( 1 )
{
    print "\n";
    print "\n";
    print "\n";
    print "\n";
    print "\n";
    print "=================================================================\n";
    print "Calling UpdateFanSpeed()...\n";
    print "=================================================================\n";
    UpdateFanSpeed();
    print "=================================================================\n";
    print "Update Complete - going to sleep for $seconds_to_sleep seconds...\n";
    print "=================================================================\n";


    sleep $seconds_to_sleep;
}
